services:
  postgres:
    container_name: ambtec-dev-db
    env_file:
      - .env
    image: postgres:16
    ports:
      - 5431:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
